# Generated by Django 5.1.1 on 2024-10-24 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='photos/defaut.png', null=True, upload_to='photos/')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('statut_matrimonial', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)')], max_length=11)),
                ('nationalite', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('date_embauche', models.DateField(default=django.utils.timezone.now)),
                ('type_salarie', models.CharField(choices=[('salarie', 'Salarié'), ('benevole', 'Bénévole'), ('freelance', 'Freelance'), ('stagiaire', 'Stagiaire'), ('direction', 'Direction'), ('assit_direction', 'Assistant Direction')], max_length=20)),
                ('statut', models.CharField(choices=[('C', 'En congée'), ('T', 'Au travail')], default='T', max_length=10)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Aucun', 'Aucun')], max_length=10, null=True)),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='fichier/')),
                ('lettre_introduction', models.FileField(blank=True, null=True, upload_to='fichier/')),
                ('bulletin_salaire', models.FileField(blank=True, null=True, upload_to='fichier/')),
                ('curriculum_vitae', models.FileField(blank=True, null=True, upload_to='fichier/')),
                ('id_facebook', models.CharField(max_length=150, null=True)),
                ('id_skype', models.CharField(max_length=150, null=True)),
                ('id_github', models.CharField(max_length=150, null=True)),
                ('id_linkedln', models.CharField(max_length=150, null=True)),
                ('jours_conge_annuels', models.PositiveIntegerField(default=15)),
                ('jours_conge_formation', models.PositiveIntegerField(default=12)),
                ('jours_conge_maternite', models.PositiveIntegerField(default=105)),
                ('jours_conge_paternite', models.PositiveIntegerField(default=3)),
                ('jours_conge_exceptionnel', models.PositiveIntegerField(default=10)),
                ('jours_conge_obligatoire', models.PositiveIntegerField(default=15)),
                ('competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.competence')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.departement')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANN', 'Annuel'), ('FOR', 'Formation'), ('MAT', 'Maternité'), ('PAT', 'Paternité'), ('EXC', 'Exceptionnel'), ('OBL', 'Obligatoire')], max_length=3)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jours_utilises', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('raison', models.TextField(blank=True, null=True)),
                ('piece_justificatif', models.FileField(blank=True, null=True, upload_to='fichier/')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('raison_refus', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.employee')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_responsables', to='personnel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Exportation')], max_length=50)),
                ('consequence', models.TextField(blank=True, null=True)),
                ('utilisateur_affecte', models.CharField(blank=True, max_length=255, null=True)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('employe', 'Employé'), ('conge', 'Congé'), ('paie', 'Paie'), ('session', 'Session'), ('privilege', 'Privilèges'), ('calendrier', 'Calendrier')], max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('conge_termine', 'Congé terminé'), ('rappel_mise_a_jour', 'Rappel de mise à jour'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('fiche_de_paie_prete', 'Fiche de paie prête'), ('mise_a_jour_document', 'Mise à jour de document'), ('avis_de_conge', 'Avis de congé'), ('demande_conge_recue', 'Demande de congé reçue'), ('connexion_reussi', 'Connéxion réussie'), ('deconnexion_reussi', 'Déconnexion réussie'), ('demande_conge', 'Demande de congé envoyer avec succes'), ('schedule_create', 'Un nouveau emploie du temps a été ajouter dans le calendrier')], max_length=20)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_global', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creat_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indemnites', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indice_anciennete', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('cotisations_salariales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotisations_patronales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_paie', models.DateField()),
                ('statut', models.CharField(choices=[('Payé', 'Payé'), ('En attente', 'En attente')], max_length=20, null=True)),
                ('date_debut', models.DateField(help_text="Début de la période d'exercice")),
                ('date_fin', models.DateField(help_text="Fin de la période d'exercice")),
                ('lot', models.DateField(help_text='Sélectionner mois et année')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('exercice', models.CharField(editable=False, max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.departement')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.poste'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('jour_debut', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, null=True)),
                ('jour_fin', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='personnel.notification')),
                ('user_affected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français')], default='fr', max_length=5)),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=5)),
                ('receive_desktop_notifications', models.BooleanField(default=True)),
                ('receive_email_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
