# Generated by Django 5.1.1 on 2024-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_employee_groupe_sanguin_employee_maladie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='jours_utilises',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_facebook',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_skype',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='date_paie',
        ),
        migrations.AlterField(
            model_name='employee',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_github',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_linkedln',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='maladie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='numero_telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('employee_create', 'Création d un nouveau employée réussi'), ('conge_termine', 'Congé terminé'), ('rappel_mise_a_jour', 'Rappel de mise à jour'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('fiche_de_paie_prete', 'Fiche de paie prête'), ('mise_a_jour_document', 'Mise à jour de document'), ('avis_de_conge', 'Avis de congé'), ('demande_conge_recue', 'Demande de congé reçue'), ('connexion_reussi', 'Connéxion réussie'), ('deconnexion_reussi', 'Déconnexion réussie'), ('demande_conge', 'Demande de congé envoyer avec succes'), ('schedule_create', 'Un nouveau emploie du temps a été ajouter dans le calendrier')], max_length=20),
        ),
    ]
