# Generated by Django 5.1.1 on 2024-10-29 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_remove_conge_jours_utilises_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paie',
            old_name='indemnites',
            new_name='indemnite_communication',
        ),
        migrations.RenameField(
            model_name='paie',
            old_name='primes',
            new_name='indemnite_stage',
        ),
        migrations.AddField(
            model_name='paie',
            name='indemnite_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_ajout', models.CharField(choices=[('prime', 'Prime'), ('indemnite', 'Indemnité'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajouts', to='personnel.paie')),
            ],
        ),
    ]
