# Generated by Django 5.1.1 on 2024-10-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_paie_salaire_brut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='cotisations_patronales',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='cotisations_salariales',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='net_a_payer',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='net_imposable',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='salaire_brut',
        ),
    ]
