# Generated by Django 5.1.1 on 2024-10-30 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_prime_paie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='indice_anciennete',
        ),
        migrations.RemoveField(
            model_name='prime',
            name='type_ajout',
        ),
        migrations.AddField(
            model_name='paie',
            name='net_a_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('employee_create', 'Création d un nouveau employée réussi'), ('conge_termine', 'Congé terminé'), ('rappel_mise_a_jour', 'Rappel de mise à jour'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', 'Congé refusé'), ('paie_create', 'Fiche de paie crée'), ('paie_delete', 'Fiche de paie a été suprimer'), ('paie_update', 'Fiche de paie a été crée'), ('paie_ready', 'Fiche de paie prête'), ('mise_a_jour_document', 'Mise à jour de document'), ('avis_de_conge', 'Avis de congé'), ('demande_conge_recue', 'Demande de congé reçue'), ('connexion_reussi', 'Connéxion réussie'), ('deconnexion_reussi', 'Déconnexion réussie'), ('demande_conge', 'Demande de congé envoyer avec succes'), ('schedule_create', 'Un nouveau emploie du temps a été ajouter dans le calendrier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paie',
            name='lot',
            field=models.DateField(default=datetime.date.today, help_text='Sélectionner mois et année'),
        ),
    ]
