# Generated by Django 5.1.1 on 2024-10-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_remove_paie_indice_anciennete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paie',
            name='lot',
        ),
    ]
