# Generated by Django 5.1.1 on 2024-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_remove_paie_lot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'permissions': [('can_conge_conge', 'Manage conge')]},
        ),
        migrations.AlterModelOptions(
            name='paie',
            options={'permissions': [('can_export_paie', 'Export paie')]},
        ),
        migrations.AlterField(
            model_name='employee',
            name='salaire_base',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historique',
            name='categorie',
            field=models.CharField(choices=[('employe', 'Employé'), ('conge', 'Congé'), ('paie', 'Paie'), ('session', 'Session'), ('privilege', 'Privilèges'), ('emploi_du_temps', 'Calendrier'), ('evenement', 'Événement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('employee_create', "Création d'un nouvel employé réussie"), ('conge_termine', 'Le congé est terminé'), ('rappel_mise_a_jour', 'Rappel pour mise à jour'), ('conge_approuve', 'Le congé a été approuvé'), ('conge_refuse', 'Le congé a été refusé'), ('paie_create', 'La fiche de paie a été créée'), ('paie_delete', 'La fiche de paie a été supprimée'), ('paie_update', 'La fiche de paie a été mise à jour'), ('paie_ready', 'La fiche de paie est prête'), ('mise_a_jour_document', 'Le document a été mis à jour'), ('avis_de_conge', 'Un avis de congé a été émis'), ('demande_conge_recue', 'La demande de congé a été reçue'), ('connexion_reussi', 'Connexion réussie'), ('deconnexion_reussi', 'Déconnexion réussie'), ('demande_conge', 'La demande de congé a été envoyée avec succès'), ('schedule_create', 'Un nouvel emploi du temps a été ajouté au calendrier'), ('schedule_delete', 'Un emploi du temps a été supprimer'), ('evenement_create', 'Un nouvel événement a été ajouté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('fr', 'Français')], default='fr', max_length=10),
        ),
    ]
