# Generated by Django 5.1.1 on 2024-11-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_alter_conge_options_alter_paie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'permissions': [('can_manage_conge', 'Manage conge')]},
        ),
    ]
