# Generated by Django 5.1.1 on 2025-01-28 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=200, verbose_name="Nom de l'article")),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('description', models.TextField(blank=True, default=None, max_length=1000, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=200, null=True, verbose_name='Réf. du facture')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé du facture')),
                ('reglement', models.CharField(blank=True, choices=[('A réception', 'A réception'), ('30 jours', '30 jours'), ('30 jours fin de mois', '30 jours fin de mois'), ('60 jours', '60 jours'), ('60 jours fin de mois', '60 jours fin de mois'), ('A commande', 'A commande'), ('A livraison', 'A livraison'), ('50/50', '50/50'), ('10 jours', '10 jours'), ('10 jours fin de mois', '10 jours fin de mois'), ('14 jours', '14 jours'), ('14 jours fin de mois', '14 jours fin de mois')], max_length=200, verbose_name='Règlement')),
                ('condition', models.CharField(blank=True, max_length=200, verbose_name='Condition')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date_facture', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date du facture')),
                ('etat_facture', models.CharField(choices=[('Impayée', 'Impayée'), ('Payé', 'Payé'), ('En cours', 'En cours'), ('Brouillon', 'Brouillon'), ('Annulé', 'Annulé')], default='Non payé', max_length=10)),
                ('services', models.JSONField(blank=True, default=None, verbose_name='Services supplémentaires')),
                ('type', models.CharField(blank=True, choices=[('Facture', 'Facture'), ('Devis', 'Devis')], default='Facture', max_length=10, null=True)),
                ('with_tva', models.BooleanField(blank=True, default=False, verbose_name='TVA')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Facture créer par ')),
            ],
        ),
    ]
