# Generated by Django 5.1.1 on 2025-01-28 06:53

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='photos/pdp_defaut.png', upload_to='photos/')),
                ('name', models.CharField(max_length=50)),
                ('commercial_name', models.CharField(blank=True, max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('type_client', models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Fourniseur', 'Fourniseur'), ('Client-Prospect', 'Client-Prospect'), ('Client-Fourniseur', 'Client-Fourniseur')], default='Client', max_length=20)),
                ('disponibilite', models.JSONField(blank=True, default=None)),
                ('description_facture', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('photo', models.TextField(blank=True, default='photos/pdp_defaut.png', max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('commercial_name', models.CharField(blank=True, max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('type_client', models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Fourniseur', 'Fourniseur'), ('Client-Prospect', 'Client-Prospect'), ('Client-Fourniseur', 'Client-Fourniseur')], default='Client', max_length=20)),
                ('disponibilite', models.JSONField(blank=True, default=None)),
                ('description_facture', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical client',
                'verbose_name_plural': 'historical clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
