# Generated by Django 5.1.1 on 2024-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='photos/pdp_defaut.png', null=True, upload_to='photos/'),
        ),
    ]
