# Generated by Django 5.1.1 on 2024-10-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_alter_customuser_photo'),
        ('accounts', '0002_historicalcustomuser'),
    ]

    operations = [
    ]
