# Generated by Django 5.1.1 on 2024-11-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20241031_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='photos/pdp_defaut.png', upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
    ]
