# Generated by Django 5.1.1 on 2024-10-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=10),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
