# Generated by Django 5.1.1 on 2024-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_rename_quantité_historicaloperationsortir_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicaloperationsortir',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='montant',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
