# Generated by Django 5.1.1 on 2024-11-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperationsortir',
            name='quantite',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='beneficiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caisse.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caisse.categorie'),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='caisse.fournisseur'),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='quantite',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, null=True),
        ),
    ]
