# Generated by Django 5.1.1 on 2025-01-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0010_alter_historicaloperationsortir_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperationsortir',
            name='beneficiaire',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisse.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='historicaloperationsortir',
            name='categorie',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisse.categorie'),
        ),
        migrations.AlterField(
            model_name='historicaloperationsortir',
            name='quantite',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='beneficiaire',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='caisse.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='caisse.categorie'),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='quantite',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
