# Generated by Django 5.1.1 on 2025-01-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0011_alter_historicaloperationsortir_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperationentrer',
            name='beneficiaire',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperationentrer',
            name='client',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationentrer',
            name='beneficiaire',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='operationentrer',
            name='client',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
