# Generated by Django 5.1.1 on 2025-01-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0012_historicaloperationentrer_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='categorie',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisse.categorie'),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.categorie'),
        ),
    ]
