# Generated by Django 5.1.1 on 2025-01-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0013_alter_historicaloperationentrer_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloperationentrer',
            old_name='beneficiaire',
            new_name='benef',
        ),
        migrations.RenameField(
            model_name='operationentrer',
            old_name='beneficiaire',
            new_name='benef',
        ),
    ]
