# Generated by Django 5.1.1 on 2025-01-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0014_rename_beneficiaire_historicaloperationentrer_benef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='benef',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='client',
            field=models.CharField(default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='description',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='benef',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='client',
            field=models.CharField(default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='description',
            field=models.CharField(max_length=75),
        ),
    ]
