# Generated by Django 5.1.1 on 2025-01-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0015_alter_historicaloperationentrer_benef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='benef',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='categorie',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisse.categorie'),
        ),
        migrations.AlterField(
            model_name='historicaloperationentrer',
            name='client',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='benef',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='caisse.categorie'),
        ),
        migrations.AlterField(
            model_name='operationentrer',
            name='client',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='beneficiaire',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='caisse.beneficiaire'),
        ),
        migrations.AlterField(
            model_name='operationsortir',
            name='fournisseur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='caisse.fournisseur'),
        ),
    ]
